name: "Antrea Daily job to generate cyclonus artifacts"
on:
  workflow_dispatch:
  schedule:
    # Daily, 3:00pm
    - cron: '00 15 * * *'

jobs:
  antrea-daily-job-artifacts:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@master
        with:
          repository: K8sbykeshed/k8s-local-dev

      - run: |
          mkdir download
          ls
          pushd ./antrea
            ./setup.sh
          popd
          ls
          DIR_CNI="antrea" ./run-cyclonus-job.sh
