name: "Antrea Daily job to generate cyclonus artifacts"
on:
  workflow_dispatch:
  schedule:
    # Daily, 3:00pm
    - cron: '00 15 * * *'

jobs:
  antrea-daily-job-artifacts:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
        with:
           path: main

      - uses: actions/checkout@master
        with:
          repository: K8sbykeshed/k8s-local-dev
          path: k8s-local-dev

      - run: |
          mkdir download

          pushd ./k8s-local-dev/antrea
            ./setup.sh
          popd

          pushd ./main          
            DIR_CNI="antrea" ./run-cyclonus-job.sh
          popd
