name: "Cilium v1.9.4 Daily job to generate cyclonus artifacts"
on:
  workflow_dispatch:
  schedule:
    # Daily, 3:00pm
    - cron: '00 15 * * *'

jobs:
  cilium-daily-job-v1-9-4-artifacts:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
        with:
           path: main

      - uses: actions/checkout@master
        with:
          repository: K8sbykeshed/k8s-local-dev
          path: k8s-local-dev

      - run: |
          pushd ./k8s-local-dev
            CILIUM_VERSION=v1.9.4 ./k8s-local-dev cilium
          popd

          pushd ./main          
            JOB_YAML="./jobs/antrea/cyclonus-job.yaml" DIR_CNI="cilium" ./run-cyclonus-job.sh
          popd

      - uses: actions/upload-artifact@v2
        with:
          name: logs
          path: ./main/downloads/
          retention-days: 60
